on:
  pull_request:
  push:
    branches:
      - 0.10

name: phpunit

jobs:
  phpunit:
    uses: spiral/gh-actions/.github/workflows/phpunit.yml@master
    with:
      os: >-
        ['ubuntu-latest']
      stability: >-
        ['prefer-lowest', 'prefer-stable']
